# Generated by Django 4.2.28 on 2026-02-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('TAKEN', 'Taken'), ('PLANNED', 'Planned/Advance')], default='TAKEN', max_length=10),
        ),
    ]
